FROM ubuntu

# Update OS
RUN apt-get update -y && DEBIAN_FRONTEND=noninteractive

# Install
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y wget curl git \
      && apt-get clean


#curl https://get.docker.io/builds/Linux/x86_64/docker-latest -o /usr/local/bin/docker
#chmod +x /usr/local/bin/docker 

ONBUILD RUN echo 'file' > /onbuild
