FROM ubuntu-upstart:trusty

# Create busybee credentials
RUN mkdir /root/.ssh
COPY drone-busybee/busybee* /root/.ssh/
RUN chmod 700 /root/.ssh && chmod 600 /root/.ssh/busybee

# Create remote busybee remote user
RUN SHD=/home/busybee/.ssh && adduser --disabled-password --gecos "" busybee && \
    mkdir $SHD && chown busybee.busybee $SHD && chmod 700 $SHD

RUN SHD=/home/busybee/.ssh && echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCdCmmPjsOBWRXc+PKdgDRrsciNjp25zTacyz8Gdkln2ma046brOYXAphhp/85DKgHtANBBt3cl4+HnpDbmAfyq2qZT7hWzAbMxtq0Sj+yyFyUdreXoe4gEKyxpV6o8p/R/XzEcawvqX/vFc5EIFmvTdamxZs9DQmOE5AZMzUB18Kerkrb0/arUcZ8iMi9Ng9a18avow+7oUFZ6Oub7ISz/dkIRojaKO/2paJZ4p+v7ZLn7Hq8TUeBkgAlx872oh8J8linhIq17zK6x4MGL8qiurp2hnfe0cuCxwcsYGy+4DfK51+E2vks6FprCIfF5hIdz26euPn67/YpM0F0b5nXF busybee@dockerunit" >> $SHD/authorized_keys && \
    chown busybee.busybee $SHD/authorized_keys

# Install
RUN DEBIAN_FRONTEND=noninteractive && apt-get update -y && \
      apt-get install -y wget curl git gdebi-core sudo \
        && apt-get clean

# Install ssh and fix directory creation (postinst fails for some reason)
RUN DEBIAN_FRONTEND=noninteractive && apt-get install -y openssh-client \
      openssh-server && mkdir /var/run/sshd

RUN echo "busybee ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/busybee && \
    chmod 440 /etc/sudoers.d/busybee
