FROM ubuntu

# Update OS
RUN apt-get update -y && DEBIAN_FRONTEND=noninteractive

# Install
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y wget curl git openssh-client \
      && apt-get clean

# Create busybee credentials
RUN mkdir /root/.ssh
COPY drone-busybee/busybee* /root/.ssh/
RUN chmod 700 /root/.ssh && chmod 600 /root/.ssh/busybee
